package cl.aligare.kie_server_aligare;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean aprobado;
	private java.util.Date fechaNacimiento;
	private java.lang.Integer ingresos;
	private java.lang.String ocupacion;

	public Applicant() {
	}

	public java.lang.Boolean getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(java.lang.Boolean aprobado) {
		this.aprobado = aprobado;
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Applicant(java.lang.Boolean aprobado, java.util.Date fechaNacimiento) {
		this.aprobado = aprobado;
		this.fechaNacimiento = fechaNacimiento;
	}

	public java.lang.Integer getIngresos() {
		return ingresos;
	}

	public void setIngresos(java.lang.Integer ingresos) {
		this.ingresos = ingresos;
	}

	public java.lang.String getOcupacion() {
		return ocupacion;
	}

	public void setOcupacion(java.lang.String ocupacion) {
		this.ocupacion = ocupacion;
	}
	
	

}